[biology]
url = 'https://fireball.ftmc.uam.es/fireballpy/fdatas/biology.tar.xz'
species = ['H', 'C', 'N', 'O', 'S']
charges_method = 'weighted_lowdin'

[biology.correction]
kind = 'dftd3'
damping = 'd3bj'
params_tweaks = {s8 = 1.80, a1 = 0.62, a2 = 2.50}

[biology_extended]
url = 'https://fireball.ftmc.uam.es/fireballpy/fdatas/biology_extended.tar.xz'
species = ['H', 'C', 'N', 'O', 'S']
charges_method = 'weighted_lowdin'

[biology_extended.correction]
kind = 'dftd3'
damping = 'd3bj'
params_tweaks = {s8 = 1.90, a1 = 0.65, a2 = 3.30}

[CHON]
url = 'https://fireball.ftmc.uam.es/fireballpy/fdatas/CHON.tar.xz'
species = ['H', 'C', 'N', 'O']
charges_method = 'mulliken_dipole_preserving'


[HCSi]
url = 'https://fireball.ftmc.uam.es/fireballpy/fdatas/HCSi.tar.xz'
species = ['HCSi']
charges_method = 'weighted_lowdin'


[Si]
url = 'https://fireball.ftmc.uam.es/fireballpy/fdatas/Si.tar.xz'
species = ['Si']
charges_method = 'weighted_lowdin'
