[biology]
url = 'http://fireball.ftmc.uam.es/biology_fireballpy.tar.gz'
species = ['H', 'C', 'N', 'O', 'S']
charges_method = 'npa'

[biology.correction]
type = 'dftd3'
parameters = {s8 = 1.80, a1 = 0.62, a2 = 2.50}

[biology_extended]
url = 'http://fireball.ftmc.uam.es/biology_extended_fireballpy.tar.gz'
species = ['H', 'C', 'N', 'O', 'S']
charges_method = 'npa'

[biology_extended.correction]
type = 'dftd3'
parameters = {s8 = 1.90, a1 = 0.65, a2 = 3.30}

[CHON]
url = 'http://fireball.ftmc.uam.es/CHON_fireballpy.tar.gz'
species = ['H', 'C', 'N', 'O']
charges_method = 'npa'
